services:
  talkvera-monitoring:
    build: .
    container_name: talkvera-monitoring
    labels:
      traefik.enable: "true"

      traefik.http.routers.monitoring-router.entrypoints: websecure
      traefik.http.routers.monitoring-router.rule: Host(`monitoring.talkvera.com`)
      traefik.http.routers.monitoring-router.service: monitoring-service
      traefik.http.routers.monitoring-router.tls.certresolver: mytlschallenge

      traefik.http.services.monitoring-service.loadbalancer.server.port: "80"

    expose:
      - "80"
    restart: always
    networks:
      - default

networks:
  default:
    external: true
    name: root_default
